# Generated by Django 4.2.6 on 2023-12-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('transfer_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='clubs.footballclub')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='clubs.footballclub')),
            ],
        ),
        migrations.CreateModel(
            name='ClubFinances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_funds', models.BigIntegerField()),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='clubs.footballclub')),
            ],
        ),
    ]
