# Generated by Django 4.2.6 on 2024-05-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='image_url',
        ),
    ]
