# Generated by Django 4.2.6 on 2023-12-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('nationality', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('club_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClubAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.footballclub')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('shooting', models.IntegerField()),
                ('heading', models.IntegerField()),
                ('tackling', models.IntegerField()),
                ('positioning', models.IntegerField()),
                ('vision', models.IntegerField()),
                ('composure', models.IntegerField()),
                ('crossing', models.IntegerField()),
                ('finishing', models.IntegerField()),
                ('freekicks', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
